language: java

sudo: false # faster builds

script:
  - gradle build
  - if [ "$TRAVIS_BRANCH" = "master" ]; then gradle sonarqube; gradle uploadArchives; fi
  - if [ "$TRAVIS_BRANCH" = "release" ]; then gradle clean release -Prelease.useAutomaticVersion=true; gradle generateChangelog; chmod +x ./push.sh && ./push.sh; fi

after_success:
- bash <(curl -s https://codecov.io/bash)